For:《Python语言与应用》<br>
By：上海大杨晓明<br>
Created date: 2020.04.02

# Chapter_07_05 基于DataFrame数据分析-2

## 10  透视表与交叉表

### （1）透视表

In [1]:
import pandas as pd
# 读取全部数据，使用默认索引
df = pd.read_excel(r'超市营业额2.xlsx')
df[:10]

     工号  姓名          日期           时段     交易额    柜台
0  1001  张三  2019-03-01   9：00-14：00  1664.0   化妆品
1  1002  李四  2019-03-01  14：00-21：00   954.0   化妆品
2  1003  王五  2019-03-01   9：00-14：00  1407.0    食品
3  1004  赵六  2019-03-01  14：00-21：00  1320.0    食品
4  1005  周七  2019-03-01   9：00-14：00   994.0   日用品
5  1006  钱八  2019-03-01  14：00-21：00  1421.0   日用品
6  1006  钱八  2019-03-01   9：00-14：00  1226.0  蔬菜水果
7  1001  张三  2019-03-01  14：00-21：00  1442.0  蔬菜水果
8  1001  张三  2019-03-02   9：00-14：00  1530.0   化妆品
9  1002  李四  2019-03-02  14：00-21：00  1395.0   化妆品

In [4]:
# 查看每人每天交易总额
dff = df.groupby(by=['姓名','日期'], as_index=False).sum()
dff[:10]

   姓名          日期    工号     交易额
0  周七  2019-03-01  1005   994.0
1  周七  2019-03-02  1005  1444.0
2  周七  2019-03-03  2010  3230.0
3  周七  2019-03-04  2010  2545.0
4  周七  2019-03-05  1005  1249.0
5  周七  2019-03-06  2010  3477.0
6  周七  2019-03-07  1005  1465.0
7  周七  2019-03-08  1005  1029.0
8  周七  2019-03-09  1005  1012.0
9  周七  2019-03-10  2010  1033.0

In [5]:
dff1 = dff.pivot(index='姓名', columns='日期', values='交易额')
dff1.iloc[:,:10]

日期,2019-03-01,2019-03-02,2019-03-03,2019-03-04,2019-03-05,2019-03-06,2019-03-07,2019-03-08,2019-03-09,2019-03-10
姓名,,,,,,,,,,
周七,994.0,1444.0,3230.0,2545.0,1249.0,3477.0,1465.0,1029.0,1012.0,1033.0
张三,3106.0,1530.0,1361.0,1216.0,2247.0,1037.0,1263.0,NaN,NaN,2496.0
李四,954.0,3044.0,1034.0,2734.0,3148.0,822.0,2030.0,2339.0,1382.0,1478.0
王五,1407.0,2115.0,1713.0,1590.0,1687.0,1200.0,1713.0,2288.0,2776.0,1135.0
赵六,1320.0,906.0,2309.0,1673.0,974.0,1245.0,2282.0,1898.0,2723.0,2647.0
钱八,2647.0,1141.0,1457.0,1402.0,1578.0,2361.0,950.0,1688.0,2205.0,NaN

In [6]:
dff2 = dff.pivot(index='日期', columns='姓名', values='交易额')
dff2.iloc[:,:]

姓名              周七       张三      李四       王五      赵六      钱八
日期
2019-03-01   994.0   3106.0   954.0   1407.0  1320.0  2647.0
2019-03-02  1444.0   1530.0  3044.0   2115.0   906.0  1141.0
2019-03-03  3230.0   1361.0  1034.0   1713.0  2309.0  1457.0
2019-03-04  2545.0   1216.0  2734.0   1590.0  1673.0  1402.0
2019-03-05  1249.0   2247.0  3148.0   1687.0   974.0  1578.0
2019-03-06  3477.0   1037.0   822.0   1200.0  1245.0  2361.0
2019-03-07  1465.0   1263.0  2030.0   1713.0  2282.0   950.0
2019-03-08  1029.0      NaN  2339.0   2288.0  1898.0  1688.0
2019-03-09  1012.0      NaN  1382.0   2776.0  2723.0  2205.0
2019-03-10  1033.0   2496.0  1478.0   1135.0  2647.0     NaN
2019-03-11  2492.0      NaN  1045.0    801.0  2486.0  3286.0
2019-03-12  2619.0   3086.0   979.0    831.0  1183.0  1530.0
2019-03-13  1969.0   2617.0    98.0   1053.0  1130.0  3218.0
2019-03-14  1387.0  13361.0   822.0   1642.0  2059.0     NaN
2019-03-15  1964.0   1035.0  2954.0   1483.0  1449.0  1085.0
2019-03-16  2133.0   1408.0  3378.0   1498.0  1008.0     0.0
2019-03-17  1022.0   1791.0   828.0   2609.0  2215.0   840.0
2019-03-18  1329.0   1378.0   824.0   2259.0  2331.0  1567.0
2019-03-19  1058.0   2220.0  1459.0   1872.0   882.0  1483.0
2019-03-20  1046.0   1866.0  2947.0   1485.0  1649.0   980.0
2019-03-21  1581.0      NaN  2416.0   1182.0  2675.0   807.0
2019-03-22  1437.0    946.0   864.0   2865.0   981.0  3058.0
2019-03-23  1523.0   2567.0  2849.0   1695.0  1603.0  1496.0
2019-03-24     NaN   1135.0  3078.0   1314.0  2927.0  2545.0
2019-03-25   865.0    114.0  2996.0   2485.0   860.0  1178.0
2019-03-26  1006.0   2599.0  2376.0   1244.0  2856.0  1360.0
2019-03-27   866.0   1649.0  1145.0    999.0  1301.0  2996.0
2019-03-28   871.0   2643.0  1070.0  10241.0  1224.0  1219.0
2019-03-29  1737.0   1523.0  2687.0   1404.0  2312.0  1639.0
2019-03-30  1070.0   1936.0  2817.0   1032.0  1571.0  1090.0
2019-03-31  2365.0      NaN  2133.0   1274.0  3390.0   812.0

In [12]:
# 交易总额低于5万元的员工前5天业绩
dff1[dff1.sum(axis=1)<50000].iloc[:,-10:]
# dff2.loc[:,dff2.sum(axis=0)<50000]

日期,2019-03-22,2019-03-23,2019-03-24,2019-03-25,2019-03-26,2019-03-27,2019-03-28,2019-03-29,2019-03-30,2019-03-31
姓名,,,,,,,,,,
周七,1437.0,1523.0,NaN,865.0,1006.0,866.0,871.0,1737.0,1070.0,2365.0
钱八,3058.0,1496.0,2545.0,1178.0,1360.0,2996.0,1219.0,1639.0,1090.0,812.0

In [13]:
# 交易总额低于5万元的员工姓名
dff1[dff1.sum(axis=1)<50000].index.values

array(['周七', '钱八'], dtype=object)

In [15]:
df[:10]

     工号  姓名          日期           时段     交易额    柜台
0  1001  张三  2019-03-01   9：00-14：00  1664.0   化妆品
1  1002  李四  2019-03-01  14：00-21：00   954.0   化妆品
2  1003  王五  2019-03-01   9：00-14：00  1407.0    食品
3  1004  赵六  2019-03-01  14：00-21：00  1320.0    食品
4  1005  周七  2019-03-01   9：00-14：00   994.0   日用品
5  1006  钱八  2019-03-01  14：00-21：00  1421.0   日用品
6  1006  钱八  2019-03-01   9：00-14：00  1226.0  蔬菜水果
7  1001  张三  2019-03-01  14：00-21：00  1442.0  蔬菜水果
8  1001  张三  2019-03-02   9：00-14：00  1530.0   化妆品
9  1002  李四  2019-03-02  14：00-21：00  1395.0   化妆品

### 使用pivot_table()方法实现

In [17]:
# 如果把只显示前5列的限制去掉，会发现最后还有一个名字为ALL的列
df.pivot_table(values='交易额', index='姓名', columns='日期',aggfunc='sum',margins=True).iloc[:,-10:]

日期,2019-03-23,2019-03-24,2019-03-25,2019-03-26,2019-03-27,2019-03-28,2019-03-29,2019-03-30,2019-03-31,All
姓名,,,,,,,,,,
周七,1523.0,NaN,865.0,1006.0,866.0,871.0,1737.0,1070.0,2365.0,47818.0
张三,2567.0,1135.0,114.0,2599.0,1649.0,2643.0,1523.0,1936.0,NaN,58130.0
李四,2849.0,3078.0,2996.0,2376.0,1145.0,1070.0,2687.0,2817.0,2133.0,58730.0
王五,1695.0,1314.0,2485.0,1244.0,999.0,10241.0,1404.0,1032.0,1274.0,58892.0
赵六,1603.0,2927.0,860.0,2856.0,1301.0,1224.0,2312.0,1571.0,3390.0,56069.0
钱八,1496.0,2545.0,1178.0,1360.0,2996.0,1219.0,1639.0,1090.0,812.0,47618.0
All,11733.0,10999.0,8498.0,11441.0,8956.0,17268.0,11302.0,9516.0,9974.0,327257.0

In [18]:
# 查看每人在各柜台的交易总额
dff = df.groupby(by=['姓名','柜台'], as_index=False).sum()
dff.pivot(index='姓名', columns='柜台', values='交易额')

柜台      化妆品      日用品     蔬菜水果       食品
姓名
周七   9516.0  12863.0  16443.0   8996.0
张三  22975.0  18629.0   7265.0   9261.0
李四  20467.0  10104.0  23263.0   4896.0
王五  10112.0  11357.0  10473.0  26950.0
赵六  12319.0  23286.0   2527.0  17937.0
钱八      NaN  11923.0  18561.0  17134.0

In [19]:
# 查看每人每天的上班次数
df.pivot_table(values='交易额', index='姓名', columns='日期',aggfunc='count',margins=True).iloc[:,-10:]

日期,2019-03-23,2019-03-24,2019-03-25,2019-03-26,2019-03-27,2019-03-28,2019-03-29,2019-03-30,2019-03-31,All
姓名,,,,,,,,,,
周七,1.0,NaN,1.0,1.0,1.0,1.0,1.0,1.0,2.0,40
张三,2.0,1.0,1.0,2.0,1.0,2.0,1.0,2.0,NaN,38
李四,2.0,2.0,2.0,2.0,1.0,1.0,2.0,2.0,2.0,47
王五,1.0,1.0,2.0,1.0,1.0,2.0,1.0,1.0,1.0,40
赵六,1.0,2.0,1.0,2.0,1.0,1.0,2.0,1.0,2.0,45
钱八,1.0,2.0,1.0,1.0,2.0,1.0,1.0,1.0,1.0,36
All,8.0,8.0,8.0,9.0,7.0,8.0,8.0,8.0,8.0,246

In [20]:
# 查看每人在各柜台的上班次数
df.pivot_table(values='交易额', index='姓名', columns='柜台',aggfunc='count',margins=True)

柜台    化妆品   日用品  蔬菜水果    食品  All
姓名
周七    8.0  11.0  14.0   7.0   40
张三   19.0   6.0   6.0   7.0   38
李四   16.0   9.0  18.0   4.0   47
王五    8.0   9.0   9.0  14.0   40
赵六   10.0  18.0   2.0  15.0   45
钱八    NaN   9.0  14.0  13.0   36
All  61.0  62.0  63.0  60.0  246

### (2) 交叉表

In [21]:
#（2）交叉表
import pandas as pd
# 读取全部数据，使用默认索引
df = pd.read_excel(r'超市营业额2.xlsx')

In [22]:
# 每人每天的上班次数
pd.crosstab(df.姓名, df.日期, margins=True).iloc[:,:5]

日期   2019-03-01  2019-03-02  2019-03-03  2019-03-04  2019-03-05
姓名
周七            1           1           2           2           1
张三            2           1           1           1           2
李四            1           2           1           2           2
王五            1           2           1           1           1
赵六            1           1           2           1           1
钱八            2           1           1           1           1
All           8           8           8           8           8

In [23]:
#每人在各柜台上班总次数
pd.crosstab(df.姓名, df.柜台, margins=True)

柜台   化妆品  日用品  蔬菜水果  食品  All
姓名
周七     9   11    14   8   42
张三    19    6     6   7   38
李四    16    9    18   4   47
王五     8    9     9  14   40
赵六    10   18     2  15   45
钱八     0    9    14  14   37
All   62   62    63  62  249

In [24]:
# 每人在各柜台交易总额
pd.crosstab(df.姓名, df.柜台, df.交易额, aggfunc='sum')

柜台      化妆品      日用品     蔬菜水果       食品
姓名
周七   9516.0  12863.0  16443.0   8996.0
张三  22975.0  18629.0   7265.0   9261.0
李四  20467.0  10104.0  23263.0   4896.0
王五  10112.0  11357.0  10473.0  26950.0
赵六  12319.0  23286.0   2527.0  17937.0
钱八      NaN  11923.0  18561.0  17134.0

In [25]:
# 每人在各柜台交易额平均值
pd.crosstab(df.姓名, df.柜台, df.交易额,aggfunc='mean').apply(lambda num: round(num,2))

柜台      化妆品      日用品     蔬菜水果       食品
姓名
周七  1189.50  1169.36  1174.50  1285.14
张三  1209.21  3104.83  1210.83  1323.00
李四  1279.19  1122.67  1292.39  1224.00
王五  1264.00  1261.89  1163.67  1925.00
赵六  1231.90  1293.67  1263.50  1195.80
钱八      NaN  1324.78  1325.79  1318.00

## 11  重采样

In [26]:
import numpy as np
import pandas as pd
# 读取全部数据，使用默认索引
df = pd.read_excel(r'超市营业额2.xlsx')

In [27]:
df[:5]

     工号  姓名          日期           时段     交易额   柜台
0  1001  张三  2019-03-01   9：00-14：00  1664.0  化妆品
1  1002  李四  2019-03-01  14：00-21：00   954.0  化妆品
2  1003  王五  2019-03-01   9：00-14：00  1407.0   食品
3  1004  赵六  2019-03-01  14：00-21：00  1320.0   食品
4  1005  周七  2019-03-01   9：00-14：00   994.0  日用品

In [28]:
df.日期 = pd.to_datetime(df.日期)

In [29]:
type(df.日期)

pandas.core.series.Series

In [30]:
# 每7天营业总额
df.resample('7D', on='日期').sum()['交易额']

日期
2019-03-01    73600.0
2019-03-08    77823.0
2019-03-15    65996.0
2019-03-22    79046.0
2019-03-29    30792.0
Name: 交易额, dtype: float64

In [31]:
# 每7天营业总额
df.resample('7D', on='日期',label='right').sum()['交易额']

日期
2019-03-08    73600.0
2019-03-15    77823.0
2019-03-22    65996.0
2019-03-29    79046.0
2019-04-05    30792.0
Name: 交易额, dtype: float64

In [32]:
# 每7天营业额平均值'.ljust(20,'='))
func = lambda num:round(num,2)
df.resample('7D', on='日期',label='right').mean().apply(func)['交易额']

日期
2019-03-08    1314.29
2019-03-15    1389.70
2019-03-22    1222.15
2019-03-29    1411.54
2019-04-05    1283.00
Freq: W-FRI, Name: 交易额, dtype: float64

In [33]:
# 每7天营业额平均值
# 注意，这里要用np.sum()，不能用内置函数sum()
# 因为内置函数sum()不能忽略缺失值
func = lambda item:round(np.sum(item)/len(item),2)
df.resample('7D', on='日期',label='right').apply(func)['交易额']

日期
2019-03-08    1314.29
2019-03-15    1365.32
2019-03-22    1178.50
2019-03-29    1411.54
2019-04-05    1283.00
Freq: W-FRI, Name: 交易额, dtype: float64

## 12  多索引

In [34]:
import pandas as pd
# 读取全部数据，使用默认索引
df = pd.read_excel(r'超市营业额2.xlsx')

In [35]:
# 删除工号一列的数据
df.drop('工号', axis=1, inplace=True)
df = df.groupby(by=['姓名', '柜台']).sum()
# 按姓名和柜台进行分组汇总
df[:10]

             交易额
姓名 柜台
周七 化妆品    9516.0
   日用品   12863.0
   蔬菜水果  16443.0
   食品     8996.0
张三 化妆品   22975.0
   日用品   18629.0
   蔬菜水果   7265.0
   食品     9261.0
李四 化妆品   20467.0
   日用品   10104.0

In [36]:
# 查看周七的汇总数据
df.loc['周七',:]

          交易额
柜台
化妆品    9516.0
日用品   12863.0
蔬菜水果  16443.0
食品     8996.0

In [37]:
# 查看周七在化妆品柜台的交易数据
df.loc[('周七', '化妆品')]

交易额    9516.0
Name: (周七, 化妆品), dtype: float64

In [38]:
# 重新读取数据，指定多个索引
df = pd.read_excel(r'超市营业额2.xlsx', index_col=[1, 5])
df

           工号          日期           时段     交易额
姓名 柜台
张三 化妆品   1001  2019-03-01   9：00-14：00  1664.0
李四 化妆品   1002  2019-03-01  14：00-21：00   954.0
王五 食品    1003  2019-03-01   9：00-14：00  1407.0
赵六 食品    1004  2019-03-01  14：00-21：00  1320.0
周七 日用品   1005  2019-03-01   9：00-14：00   994.0
钱八 日用品   1006  2019-03-01  14：00-21：00  1421.0
   蔬菜水果  1006  2019-03-01   9：00-14：00  1226.0
张三 蔬菜水果  1001  2019-03-01  14：00-21：00  1442.0
   化妆品   1001  2019-03-02   9：00-14：00  1530.0
李四 化妆品   1002  2019-03-02  14：00-21：00  1395.0
王五 食品    1003  2019-03-02   9：00-14：00   936.0
赵六 食品    1004  2019-03-02  14：00-21：00   906.0
周七 日用品   1005  2019-03-02   9：00-14：00  1444.0
钱八 日用品   1006  2019-03-02  14：00-21：00  1141.0
李四 蔬菜水果  1002  2019-03-02   9：00-14：00  1649.0
王五 蔬菜水果  1003  2019-03-02  14：00-21：00  1179.0
张三 化妆品   1001  2019-03-03   9：00-14：00  1361.0
李四 化妆品   1002  2019-03-03  14：00-21：00  1034.0
王五 食品    1003  2019-03-03   9：00-14：00  1713.0
赵六 食品    1004  2019-03-03  14：00-21：00  1236.0
周七 日用品   1005  2019-03-03   9：00-14：00  1592.0
钱八 日用品   1006  2019-03-03  14：00-21：00  1457.0
赵六 蔬菜水果  1004  2019-03-03   9：00-14：00  1073.0
周七 蔬菜水果  1005  2019-03-03  14：00-21：00  1638.0
张三 化妆品   1001  2019-03-04   9：00-14：00  1216.0
李四 化妆品   1002  2019-03-04  14：00-21：00  1629.0
王五 食品    1003  2019-03-04   9：00-14：00  1590.0
赵六 食品    1004  2019-03-04  14：00-21：00  1673.0
周七 日用品   1005  2019-03-04   9：00-14：00  1346.0
钱八 日用品   1006  2019-03-04  14：00-21：00  1402.0
...       ...         ...          ...     ...
周七 蔬菜水果  1005  2019-03-28   9：00-14：00   871.0
李四 蔬菜水果  1002  2019-03-28  14：00-21：00  1070.0
赵六 日用品   1004  2019-03-28   9：00-14：00  1224.0
王五 日用品   1003  2019-03-28  14：00-21：00  1210.0
   食品    1003  2019-03-28   9：00-14：00  9031.0
钱八 食品    1006  2019-03-28  14：00-21：00  1219.0
张三 化妆品   1001  2019-03-29  14：00-21：00  1523.0
李四 化妆品   1002  2019-03-29   9：00-14：00  1624.0
周七 蔬菜水果  1005  2019-03-29   9：00-14：00  1737.0
李四 蔬菜水果  1002  2019-03-29  14：00-21：00  1063.0
赵六 日用品   1004  2019-03-29   9：00-14：00   910.0
   日用品   1004  2019-03-29  14：00-21：00  1402.0
王五 食品    1003  2019-03-29   9：00-14：00  1404.0
钱八 食品    1006  2019-03-29  14：00-21：00  1639.0
张三 化妆品   1001  2019-03-30  14：00-21：00   850.0
李四 化妆品   1002  2019-03-30   9：00-14：00  1688.0
周七 蔬菜水果  1005  2019-03-30   9：00-14：00  1070.0
李四 蔬菜水果  1002  2019-03-30  14：00-21：00  1129.0
张三 日用品   1001  2019-03-30   9：00-14：00  1086.0
赵六 日用品   1004  2019-03-30  14：00-21：00  1571.0
王五 食品    1003  2019-03-30   9：00-14：00  1032.0
钱八 食品    1006  2019-03-30  14：00-21：00  1090.0
周七 化妆品   1005  2019-03-31  14：00-21：00  1321.0
李四 化妆品   1002  2019-03-31   9：00-14：00  1274.0
周七 蔬菜水果  1005  2019-03-31   9：00-14：00  1044.0
李四 蔬菜水果  1002  2019-03-31  14：00-21：00   859.0
赵六 日用品   1004  2019-03-31   9：00-14：00  1668.0
   日用品   1004  2019-03-31  14：00-21：00  1722.0
王五 食品    1003  2019-03-31   9：00-14：00  1274.0
钱八 食品    1006  2019-03-31  14：00-21：00   812.0

[249 rows x 4 columns]

In [39]:
# 丢弃“工号”列
df.drop('工号', axis=1, inplace=True)
df

                 日期           时段     交易额
姓名 柜台
张三 化妆品   2019-03-01   9：00-14：00  1664.0
李四 化妆品   2019-03-01  14：00-21：00   954.0
王五 食品    2019-03-01   9：00-14：00  1407.0
赵六 食品    2019-03-01  14：00-21：00  1320.0
周七 日用品   2019-03-01   9：00-14：00   994.0
钱八 日用品   2019-03-01  14：00-21：00  1421.0
   蔬菜水果  2019-03-01   9：00-14：00  1226.0
张三 蔬菜水果  2019-03-01  14：00-21：00  1442.0
   化妆品   2019-03-02   9：00-14：00  1530.0
李四 化妆品   2019-03-02  14：00-21：00  1395.0
王五 食品    2019-03-02   9：00-14：00   936.0
赵六 食品    2019-03-02  14：00-21：00   906.0
周七 日用品   2019-03-02   9：00-14：00  1444.0
钱八 日用品   2019-03-02  14：00-21：00  1141.0
李四 蔬菜水果  2019-03-02   9：00-14：00  1649.0
王五 蔬菜水果  2019-03-02  14：00-21：00  1179.0
张三 化妆品   2019-03-03   9：00-14：00  1361.0
李四 化妆品   2019-03-03  14：00-21：00  1034.0
王五 食品    2019-03-03   9：00-14：00  1713.0
赵六 食品    2019-03-03  14：00-21：00  1236.0
周七 日用品   2019-03-03   9：00-14：00  1592.0
钱八 日用品   2019-03-03  14：00-21：00  1457.0
赵六 蔬菜水果  2019-03-03   9：00-14：00  1073.0
周七 蔬菜水果  2019-03-03  14：00-21：00  1638.0
张三 化妆品   2019-03-04   9：00-14：00  1216.0
李四 化妆品   2019-03-04  14：00-21：00  1629.0
王五 食品    2019-03-04   9：00-14：00  1590.0
赵六 食品    2019-03-04  14：00-21：00  1673.0
周七 日用品   2019-03-04   9：00-14：00  1346.0
钱八 日用品   2019-03-04  14：00-21：00  1402.0
...             ...          ...     ...
周七 蔬菜水果  2019-03-28   9：00-14：00   871.0
李四 蔬菜水果  2019-03-28  14：00-21：00  1070.0
赵六 日用品   2019-03-28   9：00-14：00  1224.0
王五 日用品   2019-03-28  14：00-21：00  1210.0
   食品    2019-03-28   9：00-14：00  9031.0
钱八 食品    2019-03-28  14：00-21：00  1219.0
张三 化妆品   2019-03-29  14：00-21：00  1523.0
李四 化妆品   2019-03-29   9：00-14：00  1624.0
周七 蔬菜水果  2019-03-29   9：00-14：00  1737.0
李四 蔬菜水果  2019-03-29  14：00-21：00  1063.0
赵六 日用品   2019-03-29   9：00-14：00   910.0
   日用品   2019-03-29  14：00-21：00  1402.0
王五 食品    2019-03-29   9：00-14：00  1404.0
钱八 食品    2019-03-29  14：00-21：00  1639.0
张三 化妆品   2019-03-30  14：00-21：00   850.0
李四 化妆品   2019-03-30   9：00-14：00  1688.0
周七 蔬菜水果  2019-03-30   9：00-14：00  1070.0
李四 蔬菜水果  2019-03-30  14：00-21：00  1129.0
张三 日用品   2019-03-30   9：00-14：00  1086.0
赵六 日用品   2019-03-30  14：00-21：00  1571.0
王五 食品    2019-03-30   9：00-14：00  1032.0
钱八 食品    2019-03-30  14：00-21：00  1090.0
周七 化妆品   2019-03-31  14：00-21：00  1321.0
李四 化妆品   2019-03-31   9：00-14：00  1274.0
周七 蔬菜水果  2019-03-31   9：00-14：00  1044.0
李四 蔬菜水果  2019-03-31  14：00-21：00   859.0
赵六 日用品   2019-03-31   9：00-14：00  1668.0
   日用品   2019-03-31  14：00-21：00  1722.0
王五 食品    2019-03-31   9：00-14：00  1274.0
钱八 食品    2019-03-31  14：00-21：00   812.0

[249 rows x 3 columns]

In [40]:
# 按索引“柜台”排序，查看前12行
dff = df.sort_index(level='柜台', axis=0)
# 按柜台排序，查看前12行
dff[:12]

                日期           时段     交易额
姓名 柜台
周七 化妆品  2019-03-11   9：00-14：00   859.0
   化妆品  2019-03-11  14：00-21：00  1633.0
   化妆品  2019-03-12   9：00-14：00  1302.0
   化妆品  2019-03-12  14：00-21：00  1317.0
   化妆品  2019-03-13  14：00-21：00   922.0
   化妆品  2019-03-14  14：00-21：00     NaN
   化妆品  2019-03-15  14：00-21：00   916.0
   化妆品  2019-03-16  14：00-21：00  1246.0
   化妆品  2019-03-31  14：00-21：00  1321.0
张三 化妆品  2019-03-01   9：00-14：00  1664.0
   化妆品  2019-03-02   9：00-14：00  1530.0
   化妆品  2019-03-03   9：00-14：00  1361.0

In [41]:
# 按索引“姓名”排序，查看前12行
dff = df.sort_index(level='姓名', axis=0)
dff[:20]

                日期           时段     交易额
姓名 柜台
周七 化妆品  2019-03-11   9：00-14：00   859.0
   化妆品  2019-03-11  14：00-21：00  1633.0
   化妆品  2019-03-12   9：00-14：00  1302.0
   化妆品  2019-03-12  14：00-21：00  1317.0
   化妆品  2019-03-13  14：00-21：00   922.0
   化妆品  2019-03-14  14：00-21：00     NaN
   化妆品  2019-03-15  14：00-21：00   916.0
   化妆品  2019-03-16  14：00-21：00  1246.0
   化妆品  2019-03-31  14：00-21：00  1321.0
   日用品  2019-03-01   9：00-14：00   994.0
   日用品  2019-03-02   9：00-14：00  1444.0
   日用品  2019-03-03   9：00-14：00  1592.0
   日用品  2019-03-04   9：00-14：00  1346.0
   日用品  2019-03-05   9：00-14：00  1249.0
   日用品  2019-03-06   9：00-14：00  1699.0
   日用品  2019-03-07   9：00-14：00  1465.0
   日用品  2019-03-08   9：00-14：00  1029.0
   日用品  2019-03-09   9：00-14：00  1012.0
   日用品  2019-03-10   9：00-14：00    53.0
   日用品  2019-03-10  14：00-21：00   980.0

In [42]:
# 按索引“柜台”分组求和
dfff = dff.groupby(level='柜台').sum()
dfff.columns = ['交易额总和']
dfff

        交易额总和
柜台
化妆品   75389.0
日用品   88162.0
蔬菜水果  78532.0
食品    85174.0

In [43]:
# 按索引“姓名”分组求中值
# 按姓名分组求中值
dfff = dff.groupby(level='姓名').median()
dfff.columns = ['交易额中值']
dfff

     交易额中值
姓名
周七  1134.5
张三  1290.0
李四  1276.0
王五  1227.0
赵六  1224.0
钱八  1381.0

## 13  标准差与协方差

In [ ]:
import pandas as pd
df = pd.DataFrame({'A':[3,3,3,3,3], 'B':[1,2,3,4,5],'C':[-5,-4,15,4,5], 'D':[-50,-40,15,40,50]})
df

In [ ]:
# 平均值
df.mean()

In [ ]:
# 标准差
df.std()

In [ ]:
# 标准差的平方
df.std()**2

In [ ]:
# 协方差
df.cov()

In [ ]:
###使用标准差和协方差分析不同柜台的业绩
# 读取全部数据，使用默认索引
df = pd.read_excel(r'超市营业额2.xlsx',usecols=[1,2,3,4,5])
df

In [ ]:
# 丢弃缺失值和重复值
df.dropna(inplace=True)
df.drop_duplicates(inplace=True)

In [ ]:
# 处理异常值
df.loc[df.交易额<200, '交易额'] = 200
df.loc[df.交易额>3000, '交易额'] = 3000

In [ ]:
# 标准差
dff.std()

In [ ]:
# 协方差
dff.cov()

## 14  使用pandas的属性接口实现高级功能

In [44]:
import copy
import pandas as pd
# 读取全部数据，使用默认索引
df = pd.read_excel(r'超市营业额2.xlsx', usecols=[2, 4])  # 日期，交易额
df[:10]

           日期     交易额
0  2019-03-01  1664.0
1  2019-03-01   954.0
2  2019-03-01  1407.0
3  2019-03-01  1320.0
4  2019-03-01   994.0
5  2019-03-01  1421.0
6  2019-03-01  1226.0
7  2019-03-01  1442.0
8  2019-03-02  1530.0
9  2019-03-02  1395.0

In [45]:
# 深复制，不影响原来的df
dff = copy.deepcopy(df)

In [46]:
# 把日期列替换为周几
dff['日期'] = pd.to_datetime(df['日期']).dt.weekday_name

In [47]:
# 按周几分组，查看交易额平均值，四舍五入
# 按周几分组查看交易额平均值
dff = dff.groupby('日期').mean().apply(round)
dff.index.name = '周几'
dff

              交易额
周几
Friday     1277.0
Monday     1233.0
Saturday   1306.0
Sunday     1254.0
Thursday   1830.0
Tuesday    1258.0
Wednesday  1224.0

In [50]:
dff = copy.deepcopy(df)
dff[:10]

           日期     交易额
0  2019-03-01  1664.0
1  2019-03-01   954.0
2  2019-03-01  1407.0
3  2019-03-01  1320.0
4  2019-03-01   994.0
5  2019-03-01  1421.0
6  2019-03-01  1226.0
7  2019-03-01  1442.0
8  2019-03-02  1530.0
9  2019-03-02  1395.0

In [49]:
# 修改日期列，只保留年份和月份
dff['日期'] = dff['日期'].str.extract(r'(\d{4}-\d{2})')
# 只查看年份和月份
dff[:5]

        日期     交易额
0  2019-03  1664.0
1  2019-03   954.0
2  2019-03  1407.0
3  2019-03  1320.0
4  2019-03   994.0

In [51]:
# 按字符串形式的日期最后一位数进行分组
# 该月1、11、21、31日汇总为一组，2、12、22日为一组，以此类推
# 按日期的日进行分组查看交易额平均值
df.groupby(df['日期'].str.__getitem__(-1)).mean()

            交易额
日期
0   1178.250000
1   1263.645161
2   1273.291667
3   1316.880000
4   1801.304348
5   1222.958333
6   1292.000000
7   1215.826087
8   1508.250000
9   1265.583333

In [52]:
# 查看日期尾数为6的数据前12行
# 查看日期尾数为6的数据
df[df['日期'].str.endswith('6')]

             日期     交易额
40   2019-03-06  1037.0
41   2019-03-06   822.0
42   2019-03-06  1200.0
43   2019-03-06  1245.0
44   2019-03-06  1699.0
45   2019-03-06  1199.0
46   2019-03-06  1162.0
47   2019-03-06  1778.0
121  2019-03-16  1788.0
122  2019-03-16  1590.0
123  2019-03-16  1498.0
124  2019-03-16     NaN
125  2019-03-16  1008.0
126  2019-03-16  1246.0
127  2019-03-16   887.0
128  2019-03-16  1408.0
201  2019-03-26  1599.0
202  2019-03-26   853.0
203  2019-03-26  1006.0
204  2019-03-26  1390.0
205  2019-03-26  1746.0
206  2019-03-26  1244.0
207  2019-03-26   986.0
208  2019-03-26  1360.0
210  2019-03-26  1257.0

In [53]:
# 查看日期尾数为12的数据
# slice()接收3个参数，分别为起始位置、结束位置和步长
# 日期尾数为12的交易数据
df[df.日期.str.slice(-2)=='12']

            日期     交易额
88  2019-03-12  1183.0
89  2019-03-12   979.0
90  2019-03-12  1651.0
91  2019-03-12  1435.0
92  2019-03-12  1302.0
93  2019-03-12  1317.0
94  2019-03-12   831.0
95  2019-03-12  1530.0

In [54]:
# 日期中月份或天数包含2的交易数据第15到25行
# 日期中月份或天数包含2的交易数据
df[df.日期.str.slice(-5).str.contains('2')][15:25]

             日期     交易额
95   2019-03-12  1530.0
153  2019-03-20  1332.0
154  2019-03-20  1485.0
155  2019-03-20   980.0
156  2019-03-20  1615.0
157  2019-03-20  1037.0
158  2019-03-20  1649.0
159  2019-03-20  1046.0
160  2019-03-20   829.0
161  2019-03-21  1528.0

## 15 数据合并

### （1）concat()函数与append()方法
- contact  
`contact(a1,axis=0/1，keys=['xx','xx','xx',...])`  
其中a1表示要进行进行连接的列表数据,axis=1时表横着对数据进行连接。  
axis=0或不指定时，表将数据竖着进行连接。  
a1中要连接的数据有几个则对应几个keys，设置keys是为了在数据连接以后区分每一个原始a1中的数据。  
例：  
`a1=[b['a'],b['c']]
result=pd.concat(a1,axis=1，keys=['1','2'])`

- Append 将一行或多行数据连接到一个DataFrame上   
`a.append(a[2:],ignore_index=True)`  
表示将a中的第三行以后的数据全部添加到a中，若不指定ignore_index参数，则会把添加的数据的index保留下来，若ignore_index=Ture则会对所有的行重新自动建立索引。

In [55]:
import pandas as pd
# 读取Sheet1中全部数据，使用默认索引
df = pd.read_excel(r'超市营业额2.xlsx')

In [56]:
# 读取Sheet2中全部数据，使用默认索引
df5 = pd.read_excel(r'超市营业额2.xlsx',sheet_name='Sheet2')
df5

     工号  姓名          日期           时段   交易额    柜台
0  1001  张三  2019-04-01   9：00-14：00  1367   化妆品
1  1002  李四  2019-04-01  14：00-21：00  1005   化妆品
2  1003  王五  2019-04-01   9：00-14：00  1460    食品
3  1004  赵六  2019-04-01  14：00-21：00  1270    食品
4  1005  周七  2019-04-01   9：00-14：00  1123   日用品
5  1006  钱八  2019-04-01  14：00-21：00  1321   日用品
6  1007  孙九  2019-04-01   9：00-14：00  1364  蔬菜水果
7  1007  孙九  2019-04-01  14：00-21：00  1633  蔬菜水果

In [57]:
# 按行进行拆分
df1 = df[:3]
df2 = df[50:53]

In [58]:
# 按行进行合并，要求多个DataFrame结构相同
df3 = pd.concat([df1,df2,df5])
df3

      工号  姓名          日期           时段     交易额    柜台
0   1001  张三  2019-03-01   9：00-14：00  1664.0   化妆品
1   1002  李四  2019-03-01  14：00-21：00   954.0   化妆品
2   1003  王五  2019-03-01   9：00-14：00  1407.0    食品
50  1004  赵六  2019-03-07   9：00-14：00  1340.0    食品
51  1004  赵六  2019-03-07  14：00-21：00   942.0    食品
52  1005  周七  2019-03-07   9：00-14：00  1465.0   日用品
0   1001  张三  2019-04-01   9：00-14：00  1367.0   化妆品
1   1002  李四  2019-04-01  14：00-21：00  1005.0   化妆品
2   1003  王五  2019-04-01   9：00-14：00  1460.0    食品
3   1004  赵六  2019-04-01  14：00-21：00  1270.0    食品
4   1005  周七  2019-04-01   9：00-14：00  1123.0   日用品
5   1006  钱八  2019-04-01  14：00-21：00  1321.0   日用品
6   1007  孙九  2019-04-01   9：00-14：00  1364.0  蔬菜水果
7   1007  孙九  2019-04-01  14：00-21：00  1633.0  蔬菜水果

In [59]:
# 使用append()方法按行合并，忽略原来的索引
df4 = df1.append([df2,df5], ignore_index=True)
df4

      工号  姓名          日期           时段     交易额    柜台
0   1001  张三  2019-03-01   9：00-14：00  1664.0   化妆品
1   1002  李四  2019-03-01  14：00-21：00   954.0   化妆品
2   1003  王五  2019-03-01   9：00-14：00  1407.0    食品
3   1004  赵六  2019-03-07   9：00-14：00  1340.0    食品
4   1004  赵六  2019-03-07  14：00-21：00   942.0    食品
5   1005  周七  2019-03-07   9：00-14：00  1465.0   日用品
6   1001  张三  2019-04-01   9：00-14：00  1367.0   化妆品
7   1002  李四  2019-04-01  14：00-21：00  1005.0   化妆品
8   1003  王五  2019-04-01   9：00-14：00  1460.0    食品
9   1004  赵六  2019-04-01  14：00-21：00  1270.0    食品
10  1005  周七  2019-04-01   9：00-14：00  1123.0   日用品
11  1006  钱八  2019-04-01  14：00-21：00  1321.0   日用品
12  1007  孙九  2019-04-01   9：00-14：00  1364.0  蔬菜水果
13  1007  孙九  2019-04-01  14：00-21：00  1633.0  蔬菜水果

In [60]:
# 按列进行拆分
df6 = df.loc[:, ['姓名','柜台','交易额']]
df6

     姓名    柜台     交易额
0    张三   化妆品  1664.0
1    李四   化妆品   954.0
2    王五    食品  1407.0
3    赵六    食品  1320.0
4    周七   日用品   994.0
5    钱八   日用品  1421.0
6    钱八  蔬菜水果  1226.0
7    张三  蔬菜水果  1442.0
8    张三   化妆品  1530.0
9    李四   化妆品  1395.0
10   王五    食品   936.0
11   赵六    食品   906.0
12   周七   日用品  1444.0
13   钱八   日用品  1141.0
14   李四  蔬菜水果  1649.0
15   王五  蔬菜水果  1179.0
16   张三   化妆品  1361.0
17   李四   化妆品  1034.0
18   王五    食品  1713.0
19   赵六    食品  1236.0
20   周七   日用品  1592.0
21   钱八   日用品  1457.0
22   赵六  蔬菜水果  1073.0
23   周七  蔬菜水果  1638.0
24   张三   化妆品  1216.0
25   李四   化妆品  1629.0
26   王五    食品  1590.0
27   赵六    食品  1673.0
28   周七   日用品  1346.0
29   钱八   日用品  1402.0
..   ..   ...     ...
219  周七  蔬菜水果   871.0
220  李四  蔬菜水果  1070.0
221  赵六   日用品  1224.0
222  王五   日用品  1210.0
223  王五    食品  9031.0
224  钱八    食品  1219.0
225  张三   化妆品  1523.0
226  李四   化妆品  1624.0
227  周七  蔬菜水果  1737.0
228  李四  蔬菜水果  1063.0
229  赵六   日用品   910.0
230  赵六   日用品  1402.0
231  王五    食品  1404.0
232  钱八    食品  1639.0
233  张三   化妆品   850.0
234  李四   化妆品  1688.0
235  周七  蔬菜水果  1070.0
236  李四  蔬菜水果  1129.0
237  张三   日用品  1086.0
238  赵六   日用品  1571.0
239  王五    食品  1032.0
240  钱八    食品  1090.0
241  周七   化妆品  1321.0
242  李四   化妆品  1274.0
243  周七  蔬菜水果  1044.0
244  李四  蔬菜水果   859.0
245  赵六   日用品  1668.0
246  赵六   日用品  1722.0
247  王五    食品  1274.0
248  钱八    食品   812.0

[249 rows x 3 columns]

### （2）merge()方法与join()方法

merge类似于SQL中的join
设a1,a2为两个dataframe,二者中存在相同的键值，两个对象连接的方式有下面几种：  
(1)内连接，pd.merge(a1, a2, on='key')  
(2)左连接，pd.merge(a1, a2, on='key', how='left')  
(3)右连接，pd.merge(a1, a2, on='key', how='right')  
(4)外连接， pd.merge(a1, a2, on='key', how='outer')

In [61]:
import numpy as np
import pandas as pd
# 读取Sheet1中全部数据，使用默认索引
df1 = pd.read_excel(r'超市营业额2.xlsx')
df1[:10]

     工号  姓名          日期           时段     交易额    柜台
0  1001  张三  2019-03-01   9：00-14：00  1664.0   化妆品
1  1002  李四  2019-03-01  14：00-21：00   954.0   化妆品
2  1003  王五  2019-03-01   9：00-14：00  1407.0    食品
3  1004  赵六  2019-03-01  14：00-21：00  1320.0    食品
4  1005  周七  2019-03-01   9：00-14：00   994.0   日用品
5  1006  钱八  2019-03-01  14：00-21：00  1421.0   日用品
6  1006  钱八  2019-03-01   9：00-14：00  1226.0  蔬菜水果
7  1001  张三  2019-03-01  14：00-21：00  1442.0  蔬菜水果
8  1001  张三  2019-03-02   9：00-14：00  1530.0   化妆品
9  1002  李四  2019-03-02  14：00-21：00  1395.0   化妆品

In [63]:
# 读取Sheet3中全部数据，使用默认索引
df2 = pd.read_excel(r'超市营业额2.xlsx', sheet_name='Sheet3')
df2

     工号  姓名  职级
0  1001  张三  店长
1  1002  李四  主管
2  1003  王五  组长
3  1004  赵六  员工
4  1005  周七  员工
5  1006  钱八  员工
6  1007  孙九  员工

In [64]:
df3 = pd.merge(df1, df2)

In [65]:
# 按同名的列合并，随机查看10行数据
rows = np.random.randint(0, len(df1), 10)
df3.iloc[rows,:]

       工号  姓名          日期           时段     交易额    柜台  职级
55   1002  李四  2019-03-13  14：00-21：00    98.0   日用品  主管
122  1003  王五  2019-03-29   9：00-14：00  1404.0    食品  组长
131  1004  赵六  2019-03-06  14：00-21：00  1245.0    食品  员工
235  1006  钱八  2019-03-21   9：00-14：00   807.0  蔬菜水果  员工
89   1003  王五  2019-03-04   9：00-14：00  1590.0    食品  组长
209  1005  周七  2019-03-30   9：00-14：00  1070.0  蔬菜水果  员工
247  1006  钱八  2019-03-30  14：00-21：00  1090.0    食品  员工
195  1005  周七  2019-03-16   9：00-14：00   887.0  蔬菜水果  员工
110  1003  王五  2019-03-20  14：00-21：00  1485.0   化妆品  组长
102  1003  王五  2019-03-15   9：00-14：00  1483.0    食品  组长

In [66]:
# 按工号合并，指定其他同名列的后缀
pd.merge(df1, df2, on='工号', suffixes=['_x','_y']).iloc[rows,:]

       工号 姓名_x          日期           时段     交易额    柜台 姓名_y  职级
55   1002   李四  2019-03-13  14：00-21：00    98.0   日用品   李四  主管
122  1003   王五  2019-03-29   9：00-14：00  1404.0    食品   王五  组长
131  1004   赵六  2019-03-06  14：00-21：00  1245.0    食品   赵六  员工
235  1006   钱八  2019-03-21   9：00-14：00   807.0  蔬菜水果   钱八  员工
89   1003   王五  2019-03-04   9：00-14：00  1590.0    食品   王五  组长
209  1005   周七  2019-03-30   9：00-14：00  1070.0  蔬菜水果   周七  员工
247  1006   钱八  2019-03-30  14：00-21：00  1090.0    食品   钱八  员工
195  1005   周七  2019-03-16   9：00-14：00   887.0  蔬菜水果   周七  员工
110  1003   王五  2019-03-20  14：00-21：00  1485.0   化妆品   王五  组长
102  1003   王五  2019-03-15   9：00-14：00  1483.0    食品   王五  组长

In [67]:
# 两个表都设置工号列为索引
df1.set_index('工号').join(df2.set_index('工号'),lsuffix='_x', rsuffix='_y').iloc[rows,:]

     姓名_x          日期           时段     交易额    柜台 姓名_y  职级
工号
1002   李四  2019-03-13  14：00-21：00    98.0   日用品   李四  主管
1003   王五  2019-03-29   9：00-14：00  1404.0    食品   王五  组长
1004   赵六  2019-03-06  14：00-21：00  1245.0    食品   赵六  员工
1006   钱八  2019-03-21   9：00-14：00   807.0  蔬菜水果   钱八  员工
1003   王五  2019-03-04   9：00-14：00  1590.0    食品   王五  组长
1005   周七  2019-03-30   9：00-14：00  1070.0  蔬菜水果   周七  员工
1006   钱八  2019-03-30  14：00-21：00  1090.0    食品   钱八  员工
1005   周七  2019-03-16   9：00-14：00   887.0  蔬菜水果   周七  员工
1003   王五  2019-03-20  14：00-21：00  1485.0   化妆品   王五  组长
1003   王五  2019-03-15   9：00-14：00  1483.0    食品   王五  组长