For:《Python语言与应用》<br>
By：上海大杨晓明<br>
Created date: 2020.04.02

# Chapter_07_03 DataFrame创建

## 7.3 DataFrame

- DataFrame是Pandas的核心数据结构，表示的是**二维的矩阵数据表**，类似关系型数据库的结构，每一列可以是不同的值类型，比如数值、字符串、布尔值等等。<br>
- 可以将其视为电子表格或SQL表。<br>
- DataFrame既有**行索引(index)**， 也有 **列索引(columns)**，还有**值（values）**它可以被看做为一个共享相同索引的Series的字典。

## 1创建DataFrame对象

###  (1) 由list创建

In [1]:
import numpy as np
import pandas as pd

In [2]:
#由list和数组创建
data = {
    'name':['Jack','Mary','Tom'],
    'age':[14,15,17],
    'gender':['M','W','M']
}
fr = pd.DataFrame(data)
fr

   name  age gender
0  Jack   14      M
1  Mary   15      W
2   Tom   17      M

In [3]:
print(type(fr))
print(fr.index,'数据类型是：',type(fr.index))   #行标签
print(fr.values,'数据类型是：',type(fr.values)) #值
print(fr.columns,'数据类型是：',type(fr.columns))  #列标签

<class 'pandas.core.frame.DataFrame'>
RangeIndex(start=0, stop=3, step=1) 数据类型是： <class 'pandas.core.indexes.range.RangeIndex'>
[['Jack' 14 'M']
 ['Mary' 15 'W']
 ['Tom' 17 'M']] 数据类型是： <class 'numpy.ndarray'>
Index(['name', 'age', 'gender'], dtype='object') 数据类型是： <class 'pandas.core.indexes.base.Index'>

### (2) 由Series组成的创建

In [4]:
#由Series组成的创建
data1 = {'one':pd.Series(np.random.rand(2)),
         'two':pd.Series(np.random.rand(3)),
         }
data1

{'one': 0    0.015548
 1    0.445321
 dtype: float64, 'two': 0    0.632838
 1    0.483031
 2    0.915776
 dtype: float64}

In [5]:
fr1 = pd.DataFrame(data1)
fr1

        one       two
0  0.015548  0.632838
1  0.445321  0.483031
2       NaN  0.915776

In [6]:
data2 = {'one':pd.Series(np.random.rand(2),index=['a','b']),
         'two':pd.Series(np.random.rand(3),index=['a','b','c'])
         }

In [7]:
fr2 = pd.DataFrame(data2)
fr2

        one       two
a  0.761720  0.924795
b  0.378146  0.630896
c       NaN  0.555159

### (3) 通过二维数组创建 （常用）

In [8]:
#通过二维数组创建 （常用）
ar = np.random.rand(9).reshape(3,3)
ar

array([[0.27877744, 0.40219527, 0.62198056],
       [0.45020008, 0.81080245, 0.22242431],
       [0.51664024, 0.2627111 , 0.80717254]])

In [9]:
fr3 = pd.DataFrame(ar)
fr3

          0         1         2
0  0.278777  0.402195  0.621981
1  0.450200  0.810802  0.222424
2  0.516640  0.262711  0.807173

In [10]:
fr4 = pd.DataFrame(ar,index=['a','b','c'],columns=['s','h','j'])
fr4

          s         h         j
a  0.278777  0.402195  0.621981
b  0.450200  0.810802  0.222424
c  0.516640  0.262711  0.807173

### (4) 字典组成的列表

In [11]:
data3 = [{'one':1,'two':2,'three':3},{'four':4,'five':5,'six':6}]
data3

[{'one': 1, 'two': 2, 'three': 3}, {'four': 4, 'five': 5, 'six': 6}]

In [12]:
fr5 = pd.DataFrame(data3)
fr5

   five  four  one  six  three  two
0   NaN   NaN  1.0  NaN    3.0  2.0
1   5.0   4.0  NaN  6.0    NaN  NaN

### (5) 字典组成的字典

In [13]:
data4 = {
    'Tom':{'art':67,'english':98,'china':76},
    'Mary':{'art':45,'english':78,'china':70},
    'Lucy':{'art':58,'english':79},
        }
fr6 = pd.DataFrame(data4)
fr6

         Tom  Mary  Lucy
art       67    45  58.0
china     76    70   NaN
english   98    78  79.0

## 2 DataFrame查看

#### （1）head(),tail()函数
可以使用head方法查看DataFrame对象的前5行，用tail方法查看后5行。或者head(3)，tail(3)指定查看行数：

In [14]:
data1 = {'state':['beijing','beijing','beijing','shanghai','shanghai','shanghai'],
 'year':[2000,2001,2002,2001,2002,2003],
 'pop':[1.5, 1.7,3.6,2.4,2.9,3.2]}
df4 = pd.DataFrame(data1)
df4

      state  year  pop
0   beijing  2000  1.5
1   beijing  2001  1.7
2   beijing  2002  3.6
3  shanghai  2001  2.4
4  shanghai  2002  2.9
5  shanghai  2003  3.2

In [19]:
df4.head(2)

     state  year  pop
0  beijing  2000  1.5
1  beijing  2001  1.7

In [17]:
df4.tail(3)

      state  year  pop
3  shanghai  2001  2.4
4  shanghai  2002  2.9
5  shanghai  2003  3.2

#### (2)列排序
DataFrame对象中的state/year/pop，其实就是列索引，可以在创建的时候使用参数名columns指定它们的先后顺序：

In [20]:
pd.DataFrame(data1, columns=['year','state','pop'])

   year     state  pop
0  2000   beijing  1.5
1  2001   beijing  1.7
2  2002   beijing  3.6
3  2001  shanghai  2.4
4  2002  shanghai  2.9
5  2003  shanghai  3.2

#### （3）定行索引

当然，也可以使用参数名index指定行索引：

In [21]:
df = pd.DataFrame(np.random.rand(12).reshape(3,4)*100,
                  index=['one','two','three'],columns=['a','b','c','d']
                  )
df2 = pd.DataFrame(np.random.rand(12).reshape(3,4)*100,
                  columns=['a','b','c','d']
                  )
 
print(df)
print(df2)

               a          b          c          d
one    91.726881  54.985534   7.132064  51.895058
two    86.270404  10.409711  18.960431  96.780954
three  14.876732  66.287378  66.298011  43.930412
           a          b          c          d
0  70.231054  71.304295  32.437434   0.311217
1  48.999583  63.925449  20.258865  98.047901
2  63.556528  91.821674  13.690858   4.770291

In [22]:
data = df['a']
data1 = df[['a','b']]
print('data',data)
print('data1',data1)     #选择列

data one      91.726881
two      86.270404
three    14.876732
Name: a, dtype: float64
data1                a          b
one    91.726881  54.985534
two    86.270404  10.409711
three  14.876732  66.287378

In [23]:
data3 = df.loc['one']    #按index选择行,iloc
data4 = df.loc[['three','one']]
print('data3',data3)
print('data4',data4)   #选择行

data3 a    91.726881
b    54.985534
c     7.132064
d    51.895058
Name: one, dtype: float64
data4                a          b          c          d
three  14.876732  66.287378  66.298011  43.930412
one    91.726881  54.985534   7.132064  51.895058

In [24]:
data5 = df.iloc[-1]  #按整数位置选择行
print('data5',data5)

data5 a    14.876732
b    66.287378
c    66.298011
d    43.930412
Name: three, dtype: float64

In [ ]:
print("单标签索引")
print(df.loc['one'])

In [26]:
df2.loc[1]

a    48.999583
b    63.925449
c    20.258865
d    98.047901
Name: 1, dtype: float64

In [ ]:
df

In [27]:
df.loc[['two','one']]

             a          b          c          d
two  86.270404  10.409711  18.960431  96.780954
one  91.726881  54.985534   7.132064  51.895058

In [ ]:
df2

In [ ]:
df2.loc[[2,1]]

In [ ]:
print("切片索引/n")
print(df.loc['one':'two'])
print(df2.loc[1:2])

#### (4)使用columns列索引来检索一列：

In [28]:
data1 = {'state':['beijing','beijing','beijing','shanghai','shanghai','shanghai'],
 'year':[2000,2001,2002,2001,2002,2003],
 'pop':[1.5, 1.7,3.6,2.4,2.9,3.2]}
df5 = pd.DataFrame(data1, columns=['year','state','pop'],index=['a','b','c','d','e','f'])
df5

   year     state  pop
a  2000   beijing  1.5
b  2001   beijing  1.7
c  2002   beijing  3.6
d  2001  shanghai  2.4
e  2002  shanghai  2.9
f  2003  shanghai  3.2

## 3 DataFrame修改

### （1）DataFrame对象追加列

In [31]:
df5['debt'] = 12
df5

   year     state  pop  debt
a  2000   beijing  1.5    12
b  2001   beijing  1.7    12
c  2002   beijing  3.6    12
d  2001  shanghai  2.4    12
e  2002  shanghai  2.9    12
f  2003  shanghai  3.2    12

In [32]:
df5['debt'] = np.arange(1,7)
df5

   year     state  pop  debt
a  2000   beijing  1.5     1
b  2001   beijing  1.7     2
c  2002   beijing  3.6     3
d  2001  shanghai  2.4     4
e  2002  shanghai  2.9     5
f  2003  shanghai  3.2     6

In [33]:
val = pd.Series([1,2,3],index = ['c','d','f'])
df5['debt'] = val
df5  # 缺失值以NaN填补

   year     state  pop  debt
a  2000   beijing  1.5   NaN
b  2001   beijing  1.7   NaN
c  2002   beijing  3.6   1.0
d  2001  shanghai  2.4   2.0
e  2002  shanghai  2.9   NaN
f  2003  shanghai  3.2   3.0

#### （2）给DataFrame追加行

In [34]:
data = {'state':['beijing','beijing','beijing','shanghai','shanghai','shanghai'],
'year':[2000,2001,2002,2001,2002,2003],
'pop':[1.5, 1.7,3.6,2.4,2.9,3.2]}

df = pd.DataFrame(data,index=list('abcdef'))
df

      state  year  pop
a   beijing  2000  1.5
b   beijing  2001  1.7
c   beijing  2002  3.6
d  shanghai  2001  2.4
e  shanghai  2002  2.9
f  shanghai  2003  3.2

In [35]:
df1 = df.loc['a']

In [36]:
df.append(df1)

      state  year  pop
a   beijing  2000  1.5
b   beijing  2001  1.7
c   beijing  2002  3.6
d  shanghai  2001  2.4
e  shanghai  2002  2.9
f  shanghai  2003  3.2
a   beijing  2000  1.5

In [37]:
df

      state  year  pop
a   beijing  2000  1.5
b   beijing  2001  1.7
c   beijing  2002  3.6
d  shanghai  2001  2.4
e  shanghai  2002  2.9
f  shanghai  2003  3.2

#### （3）使用del方法删除指定的列：

In [38]:
df['new'] = df.state=='beijing'
df

      state  year  pop    new
a   beijing  2000  1.5   True
b   beijing  2001  1.7   True
c   beijing  2002  3.6   True
d  shanghai  2001  2.4  False
e  shanghai  2002  2.9  False
f  shanghai  2003  3.2  False

In [40]:
df 
# 要注意的是我们有时候不能这么调用df的某个列，并执行某个操作。这是个坑。

      state  year  pop    new
a   beijing  2000  1.5   True
b   beijing  2001  1.7   True
c   beijing  2002  3.6   True
d  shanghai  2001  2.4  False
e  shanghai  2002  2.9  False
f  shanghai  2003  3.2  False

In [41]:
del df['new']

In [42]:
df

      state  year  pop
a   beijing  2000  1.5
b   beijing  2001  1.7
c   beijing  2002  3.6
d  shanghai  2001  2.4
e  shanghai  2002  2.9
f  shanghai  2003  3.2

> 需要注意的是：从DataFrame中选取的列是数据的视图，而不是拷贝。因此，对选取列的修改会反映到DataFrame上。如果需要复制，应当使用copy方法。

#### (4)将DataFrame进行转置：

In [43]:
df.T

             a        b        c         d         e         f
state  beijing  beijing  beijing  shanghai  shanghai  shanghai
year      2000     2001     2002      2001      2002      2003
pop        1.5      1.7      3.6       2.4       2.9       3.2

In [44]:
df

      state  year  pop
a   beijing  2000  1.5
b   beijing  2001  1.7
c   beijing  2002  3.6
d  shanghai  2001  2.4
e  shanghai  2002  2.9
f  shanghai  2003  3.2

#### (5)DataFrame对象同样具有列名、索引名，也可以查看values：

In [45]:
df.index.name = 'order'
df.columns.name='key'
df

key       state  year  pop
order
a       beijing  2000  1.5
b       beijing  2001  1.7
c       beijing  2002  3.6
d      shanghai  2001  2.4
e      shanghai  2002  2.9
f      shanghai  2003  3.2

In [46]:
df.values

array([['beijing', 2000, 1.5],
       ['beijing', 2001, 1.7],
       ['beijing', 2002, 3.6],
       ['shanghai', 2001, 2.4],
       ['shanghai', 2002, 2.9],
       ['shanghai', 2003, 3.2]], dtype=object)

最后，DataFrame有一个Series所不具备的方法，那就是info！通过这个方法，可以看到DataFrame的一些整体信息情况：

In [47]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 6 entries, a to f
Data columns (total 3 columns):
state    6 non-null object
year     6 non-null int64
pop      6 non-null float64
dtypes: float64(1), int64(1), object(1)
memory usage: 352.0+ bytes